### ISSUE TITLE
status code 400

### ISSUE THREAD

**Issue by ClayGminx** [lamini-ai/lamini#26]
When I run the following code:

```Python
chatgpt = BasicModelRunner("chat-gpt")
print(chatgpt("Tell me how to train my dog to sit"))
```

Output

![图片](https://github.com/lamini-ai/lamini/assets/62022018/f49491b0-ffc2-4135-8e81-d54e11843ade)

**Comment by safazaidmalik** [comment]
I am also facing the same issue on `model.get_answer()`

```
from llama import QuestionAnswerModel
!wget -q -O "seed_lamini_docs.jsonl" "https://drive.google.com/uc?export=download&id=1SfGp1tVuLTs0WYDugZcxX-EHrmDtYrYJ"
model = QuestionAnswerModel(model_name="EleutherAI/pythia-410m-v0")
model.train(enable_peft=True)
model.get_answer("How can I add data to Lamini?")
```

![image](https://github.com/lamini-ai/lamini/assets/75358020/ee054e9a-b410-4342-a8c9-9785979bafe8)

**Comment by ninazwei90** [comment]
@ClayGminx @safazaidmalik thank you both for posting this issue! We recently had a big upgrade of our system -- the error is very likely because of that. Can you try the colab examples again? We also added more examples, including some very easy-to-run SDKs https://www.lamini.ai/examples 

feel free to email me if you run into more issues: nina@lamini.ai. We appreciate your feedback too!

**Comment by ClayGminx** [comment]
Soga.

**Comment by ninazwei90** [comment]
@ClayGminx @safazaidmalik We knew what caused this issue -- we already had a fix and we will push the new fix on Thursday. you should be able to run without any problems. i will update here too. Appreciate your understanding for this inconvenience!

**Comment by safazaidmalik** [comment]
Thank you for updating on this issue!

**Comment by ninazwei90** [comment]
Hi all, this should be fixed! Please try again https://www.lamini.ai/examples. Do reach out if you have any questions nina@lamini.ai
